name: Build, Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Node packages
      run: npm install
    - name: Install Playwright packages
      run: npx playwright install
    - name: Replace the config settings
      run: echo "export const settings = { host:\"http://localhost:3030\" };" > src/config.js
    - name: Run server
      run: npm run server &
    - name: Run client
      run: npm start &
    - name: Start tests
      run: npm test

  deploy-backend:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Deploy backend
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_TOKEN }}
          wait-for-success: true

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend

    steps:
      - name: Deploy frontend
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.CLIENT_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_TOKEN }}
          wait-for-success: true
